using System;
using System.Collections.Generic;

namespace scorpioweb.Models
{
    public partial class Adolescentes
    {
        public int IdAdolescente { get; set; }
        public string Nombre { get; set; }
        public int Edad { get; set; }
        public string Genero { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string Estadocivil { get; set; }
        public string Duracionestadocivil { get; set; }
        public string EstadoNac { get; set; }
        public string MunicipioNac { get; set; }
        public string Nacionalidad { get; set; }
        public string HablaEsp { get; set; }
        public string DomicilioAct { get; set; }
        public string EstadoRad { get; set; }
        public string MunicipioRad { get; set; }
        public string TipoPropiedad { get; set; }
        public string DomDur { get; set; }
        public string DomUrban { get; set; }
        public string ResidenciaHabitual { get; set; }
        public string TiempoRad { get; set; }
        public string DomicilioSec { get; set; }
        public string DireccionDomsec { get; set; }
        public string CambioDom { get; set; }
        public string DomicilioAnt { get; set; }
        public string NombrePadre { get; set; }
        public string DomicilioPadre { get; set; }
        public string NombreMadre { get; set; }
        public string DomicilioMadre { get; set; }
        public string VivePadres { get; set; }
        public string Tutor { get; set; }
        public string NombreTutor { get; set; }
        public string DomicilioTutor { get; set; }
        public string TutorRelacion { get; set; }
        public int PersonasVive { get; set; }
        public string TiempoFam { get; set; }
        public string DependientesEco { get; set; }
        public string RelacionDep { get; set; }
        public string Estudia { get; set; }
        public string InstitucionEst { get; set; }
        public string DireccionEst { get; set; }
        public string HorarioEscuela { get; set; }
        public string TelefonoEscuela { get; set; }
        public string UltimoGradoEstudios { get; set; }
        public string Trabaja { get; set; }
        public string Ocupacion { get; set; }
        public string LugarTrab { get; set; }
        public string DireccionTrab { get; set; }
        public string TiempoTrab { get; set; }
        public string Salario { get; set; }
        public string ParticipaGrupo { get; set; }
        public string GrupoPert { get; set; }
        public string TiempoGrupo { get; set; }
        public string LugarActividad { get; set; }
        public string FamEst { get; set; }
        public string FreqFamEst { get; set; }
        public string FamPais { get; set; }
        public string FreqFamPais { get; set; }
        public string Documentacion { get; set; }
        public string Viajahabitualmente { get; set; }
        public string Tiempoviajes { get; set; }
        public string Visa { get; set; }
        public string Lugaresviaje { get; set; }
        public string Motivoviajes { get; set; }
        public string Pasaporte { get; set; }
        public string Enfermedad { get; set; }
        public string TipoEnfermedad { get; set; }
        public string NombreEnfermedad { get; set; }
        public string ConsumeDrog { get; set; }
        public string DrogasCon { get; set; }
        public string FreqDrog { get; set; }
        public string Tratamiento { get; set; }
        public string VictimaDir { get; set; }
        public string VictimaDom { get; set; }
        public string AmenazasVictima { get; set; }
        public string Cercania { get; set; }
        public string Reubicacion { get; set; }
        public string RelacionVict { get; set; }
        public string DelitoVict { get; set; }
        public string CoDetenidios { get; set; }
        public string RelacionDet { get; set; }
        public string Amenazadetenido { get; set; }
        public string Testigos { get; set; }
        public string RelacionTest { get; set; }
        public string Amenazatestigo { get; set; }
        public string RelacionLugar { get; set; }
        public string VerificacionDomSec { get; set; }
        public string Cooperacion { get; set; }
        public string AmenazasTca { get; set; }
        public string CumplimientoProcesos { get; set; }
        public string Verificacion1 { get; set; }
        public string Observaciones1 { get; set; }
        public string Verificacion2 { get; set; }
        public string Observaciones2 { get; set; }
        public string Verificacion3 { get; set; }
        public string Observaciones3 { get; set; }
        public string Verificacion4 { get; set; }
        public string Observaciones4 { get; set; }
        public string Verificacion5 { get; set; }
        public string Observaciones5 { get; set; }
        public string Verificacion6 { get; set; }
        public string Observaciones6 { get; set; }
        public string Verificacion7 { get; set; }
        public string Observaciones7 { get; set; }
        public string Verificacion8 { get; set; }
        public string Observaciones8 { get; set; }
        public string Folio { get; set; }
        public string Usuario { get; set; }
        public string QuienVerifica { get; set; }
        public string ParentescoVefifica { get; set; }
    }
}
