// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using scorpioweb.Models;
using System;

namespace scorpioweb.Migrations
{
    [DbContext(typeof(penas2Context))]
    [Migration("20201202180957_Local")]
    partial class Local
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("scorpioweb.Models.Abandonoestado", b =>
                {
                    b.Property<int>("IdAbandonoEstado")
                        .HasColumnName("idAbandonoEstado")
                        .HasColumnType("int(11)");

                    b.Property<int?>("Cuantos")
                        .HasColumnType("int(5)");

                    b.Property<string>("DocumentacionSalirPais")
                        .HasMaxLength(2);

                    b.Property<string>("FamiliaresFuera")
                        .HasMaxLength(2);

                    b.Property<string>("LugaresViaje")
                        .HasMaxLength(200);

                    b.Property<string>("LugaresVivido")
                        .HasMaxLength(200);

                    b.Property<string>("MotivoViaje")
                        .HasMaxLength(200);

                    b.Property<string>("MotivoVivido")
                        .HasMaxLength(200);

                    b.Property<string>("Pasaporte")
                        .HasMaxLength(2);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("TiempoViaje")
                        .HasMaxLength(100);

                    b.Property<string>("TiempoVivido")
                        .HasMaxLength(100);

                    b.Property<string>("ViajaHabitual")
                        .HasMaxLength(2);

                    b.Property<string>("Visa")
                        .HasColumnName("VISA")
                        .HasMaxLength(2);

                    b.Property<string>("VividoFuera")
                        .HasMaxLength(2);

                    b.HasKey("IdAbandonoEstado");

                    b.ToTable("abandonoestado");
                });

            modelBuilder.Entity("scorpioweb.Models.Actividadsocial", b =>
                {
                    b.Property<int>("IdActividadSocial")
                        .HasColumnName("idActividadSocial")
                        .HasColumnType("int(11)");

                    b.Property<string>("Horario")
                        .HasMaxLength(100);

                    b.Property<string>("Lugar")
                        .HasMaxLength(150);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100);

                    b.Property<string>("SePuedeEnterar")
                        .HasMaxLength(2);

                    b.Property<string>("Telefono")
                        .HasMaxLength(10);

                    b.Property<string>("TipoActividad")
                        .HasMaxLength(150);

                    b.HasKey("IdActividadSocial");

                    b.ToTable("actividadsocial");
                });

            modelBuilder.Entity("scorpioweb.Models.Aer", b =>
                {
                    b.Property<int>("IdAer")
                        .HasColumnName("idAER");

                    b.Property<int>("SupervisionIdSupervision")
                        .HasColumnName("Supervision_idSupervision");

                    b.Property<string>("CuentaEvaluacion")
                        .HasMaxLength(2);

                    b.Property<string>("EvaluadorCaso")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime");

                    b.Property<string>("RiesgoDetectado")
                        .HasMaxLength(45);

                    b.Property<string>("RiesgoObstaculizacion")
                        .HasMaxLength(45);

                    b.Property<string>("RiesgoSustraccion")
                        .HasMaxLength(45);

                    b.Property<string>("RiesgoVictima")
                        .HasMaxLength(45);

                    b.HasKey("IdAer", "SupervisionIdSupervision");

                    b.HasIndex("SupervisionIdSupervision")
                        .HasName("fk_aer_Supervision_idx");

                    b.ToTable("aer");
                });

            modelBuilder.Entity("scorpioweb.Models.Archivo", b =>
                {
                    b.Property<int>("IdArchivo")
                        .HasColumnName("idArchivo");

                    b.Property<string>("AreaPrestamo")
                        .HasMaxLength(70);

                    b.Property<string>("CarpetaEjecucion")
                        .HasMaxLength(45);

                    b.Property<string>("CausaPenal")
                        .HasMaxLength(45);

                    b.Property<string>("Delito")
                        .HasMaxLength(120);

                    b.Property<string>("Envia")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("FechaAcuerdo")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaPrestamo")
                        .HasColumnType("datetime");

                    b.Property<int?>("NoArchivo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(120);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250);

                    b.Property<string>("Prestado")
                        .HasMaxLength(2);

                    b.Property<string>("Sentencia")
                        .HasMaxLength(120);

                    b.Property<string>("Situacion")
                        .HasMaxLength(45);

                    b.HasKey("IdArchivo");

                    b.ToTable("archivo");
                });

            modelBuilder.Entity("scorpioweb.Models.Asientofamiliar", b =>
                {
                    b.Property<int>("IdAsientoFamiliar")
                        .HasColumnName("idAsientoFamiliar")
                        .HasColumnType("int(11)");

                    b.Property<string>("Dependencia")
                        .HasMaxLength(2);

                    b.Property<string>("DependenciaExplica")
                        .HasMaxLength(250);

                    b.Property<string>("Domicilio")
                        .HasMaxLength(200);

                    b.Property<int?>("Edad")
                        .HasColumnType("int(11)");

                    b.Property<string>("EnteradoProceso")
                        .HasMaxLength(2);

                    b.Property<string>("HorarioLocalizacion")
                        .HasMaxLength(200);

                    b.Property<string>("Nombre")
                        .HasMaxLength(150);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("PuedeEnterarse")
                        .HasMaxLength(2);

                    b.Property<string>("Relacion")
                        .HasMaxLength(45);

                    b.Property<string>("Sexo")
                        .HasMaxLength(1);

                    b.Property<string>("Telefono")
                        .HasMaxLength(10);

                    b.Property<string>("TiempoHabitando")
                        .HasMaxLength(45);

                    b.Property<string>("Tipo")
                        .HasMaxLength(45);

                    b.Property<string>("VivenJuntos")
                        .HasMaxLength(2);

                    b.HasKey("IdAsientoFamiliar");

                    b.ToTable("asientofamiliar");
                });

            modelBuilder.Entity("scorpioweb.Models.Cambiodeobligaciones", b =>
                {
                    b.Property<int>("IdCambiodeObligaciones")
                        .HasColumnName("idCambiodeObligaciones");

                    b.Property<int>("SupervisionIdSupervision")
                        .HasColumnName("Supervision_idSupervision");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime");

                    b.Property<string>("MotivoAprobacion")
                        .HasMaxLength(200);

                    b.Property<string>("SeDioCambio")
                        .HasMaxLength(2);

                    b.HasKey("IdCambiodeObligaciones", "SupervisionIdSupervision");

                    b.HasIndex("SupervisionIdSupervision")
                        .HasName("fk_CambiodeObligaciones_Supervision_idx");

                    b.ToTable("cambiodeobligaciones");
                });

            modelBuilder.Entity("scorpioweb.Models.Causapenal", b =>
                {
                    b.Property<int>("IdCausaPenal")
                        .HasColumnName("idCausaPenal");

                    b.Property<string>("Cambio")
                        .HasMaxLength(2);

                    b.Property<string>("CausaPenal")
                        .HasMaxLength(9);

                    b.Property<string>("Cnpp")
                        .HasColumnName("CNPP")
                        .HasMaxLength(2);

                    b.Property<string>("Distrito")
                        .HasMaxLength(20);

                    b.Property<string>("Juez")
                        .HasMaxLength(100);

                    b.HasKey("IdCausaPenal");

                    b.ToTable("causapenal");
                });

            modelBuilder.Entity("scorpioweb.Models.Cierredecaso", b =>
                {
                    b.Property<int>("IdCierreDeCaso")
                        .HasColumnName("idCierreDeCaso");

                    b.Property<int>("SupervisionIdSupervision")
                        .HasColumnName("Supervision_idSupervision");

                    b.Property<string>("Autorizo")
                        .HasMaxLength(45);

                    b.Property<string>("ComoConcluyo")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NoArchivo")
                        .HasMaxLength(45);

                    b.Property<string>("SeCerroCaso")
                        .HasMaxLength(2);

                    b.HasKey("IdCierreDeCaso", "SupervisionIdSupervision");

                    b.HasIndex("SupervisionIdSupervision")
                        .HasName("fk_CierredeCaso_Supervision");

                    b.ToTable("cierredecaso");
                });

            modelBuilder.Entity("scorpioweb.Models.Consumosustancias", b =>
                {
                    b.Property<int>("IdConsumoSustancias")
                        .HasColumnName("idConsumoSustancias")
                        .HasColumnType("int(11)");

                    b.Property<string>("Cantidad")
                        .HasMaxLength(45);

                    b.Property<string>("Consume")
                        .HasMaxLength(45);

                    b.Property<string>("Frecuencia")
                        .HasMaxLength(45);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(400);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("Sustancia")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("UltimoConsumo")
                        .HasColumnType("datetime");

                    b.HasKey("IdConsumoSustancias");

                    b.ToTable("consumosustancias");
                });

            modelBuilder.Entity("scorpioweb.Models.Delito", b =>
                {
                    b.Property<int>("IdDelito")
                        .HasColumnName("idDelito");

                    b.Property<int>("CausaPenalIdCausaPenal")
                        .HasColumnName("CausaPenal_idCausaPenal");

                    b.Property<string>("EspecificarDelito")
                        .HasMaxLength(45);

                    b.Property<string>("Modalidad")
                        .HasMaxLength(45);

                    b.Property<string>("Tipo")
                        .HasMaxLength(45);

                    b.HasKey("IdDelito");

                    b.ToTable("delito");
                });

            modelBuilder.Entity("scorpioweb.Models.Domicilio", b =>
                {
                    b.Property<int>("IdDomicilio")
                        .HasColumnName("idDomicilio")
                        .HasColumnType("int(11)");

                    b.Property<string>("Calle")
                        .HasMaxLength(200);

                    b.Property<string>("Cp")
                        .HasColumnName("CP")
                        .HasMaxLength(45);

                    b.Property<string>("DomcilioSecundario")
                        .HasMaxLength(45);

                    b.Property<string>("Estado")
                        .HasMaxLength(45);

                    b.Property<string>("Horario")
                        .HasMaxLength(100);

                    b.Property<string>("Municipio")
                        .HasMaxLength(45);

                    b.Property<string>("No")
                        .HasMaxLength(45);

                    b.Property<string>("NombreCf")
                        .HasColumnName("NombreCF")
                        .HasMaxLength(45);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(400);

                    b.Property<string>("Pais")
                        .HasMaxLength(45);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("Referencias")
                        .HasMaxLength(300);

                    b.Property<string>("ResidenciaHabitual")
                        .HasMaxLength(45);

                    b.Property<string>("Temporalidad")
                        .HasMaxLength(45);

                    b.Property<string>("TipoDomicilio")
                        .HasMaxLength(45);

                    b.Property<string>("TipoUbicacion")
                        .HasMaxLength(45);

                    b.HasKey("IdDomicilio");

                    b.ToTable("domicilio");
                });

            modelBuilder.Entity("scorpioweb.Models.Domiciliosecundario", b =>
                {
                    b.Property<int>("IdDomicilioSecundario")
                        .HasColumnName("idDomicilioSecundario")
                        .HasColumnType("int(11)");

                    b.Property<string>("Calle")
                        .HasMaxLength(200);

                    b.Property<string>("Cp")
                        .HasColumnName("CP")
                        .HasMaxLength(45);

                    b.Property<string>("Estado")
                        .HasMaxLength(45);

                    b.Property<string>("Horario")
                        .HasMaxLength(100);

                    b.Property<int>("IdDomicilio")
                        .HasColumnName("idDomicilio")
                        .HasColumnType("int(11)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(100);

                    b.Property<string>("Municipio")
                        .HasMaxLength(45);

                    b.Property<string>("No")
                        .HasMaxLength(45);

                    b.Property<string>("NombreCf")
                        .HasColumnName("NombreCF")
                        .HasMaxLength(100);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300);

                    b.Property<string>("Pais")
                        .HasMaxLength(45);

                    b.Property<string>("Referencias")
                        .HasMaxLength(300);

                    b.Property<string>("ResidenciaHabitual")
                        .HasMaxLength(2);

                    b.Property<string>("Temporalidad")
                        .HasMaxLength(45);

                    b.Property<string>("TipoDomicilio")
                        .HasMaxLength(45);

                    b.Property<string>("TipoUbicacion")
                        .HasMaxLength(45);

                    b.HasKey("IdDomicilioSecundario");

                    b.ToTable("domiciliosecundario");
                });

            modelBuilder.Entity("scorpioweb.Models.Estados", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnName("estado")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("estados");
                });

            modelBuilder.Entity("scorpioweb.Models.Estudios", b =>
                {
                    b.Property<int>("IdEstudios")
                        .HasColumnName("idEstudios")
                        .HasColumnType("int(11)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150);

                    b.Property<string>("Estudia")
                        .HasMaxLength(45);

                    b.Property<string>("GradoEstudios")
                        .HasMaxLength(45);

                    b.Property<string>("Horario")
                        .HasMaxLength(100);

                    b.Property<string>("InstitucionE")
                        .HasMaxLength(150);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(45);

                    b.HasKey("IdEstudios");

                    b.ToTable("estudios");
                });

            modelBuilder.Entity("scorpioweb.Models.Familiaresforaneos", b =>
                {
                    b.Property<int>("IdFamiliaresForaneos")
                        .HasColumnName("idFamiliaresForaneos")
                        .HasColumnType("int(11)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int(11)");

                    b.Property<string>("EnteradoProceso")
                        .HasMaxLength(2);

                    b.Property<string>("Estado")
                        .HasMaxLength(70);

                    b.Property<string>("FrecuenciaContacto")
                        .HasMaxLength(45);

                    b.Property<string>("Nombre")
                        .HasMaxLength(150);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200);

                    b.Property<string>("Pais")
                        .HasMaxLength(45);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("PuedeEnterarse")
                        .HasMaxLength(2);

                    b.Property<string>("Relacion")
                        .HasMaxLength(45);

                    b.Property<string>("Sexo")
                        .HasMaxLength(1);

                    b.Property<string>("Telefono")
                        .HasMaxLength(10);

                    b.Property<string>("TiempoConocerlo")
                        .HasMaxLength(45);

                    b.HasKey("IdFamiliaresForaneos");

                    b.ToTable("familiaresforaneos");
                });

            modelBuilder.Entity("scorpioweb.Models.Firmas", b =>
                {
                    b.Property<int>("Idfirmas")
                        .HasColumnName("idfirmas")
                        .HasColumnType("int(11)");

                    b.Property<string>("Codigo")
                        .HasColumnName("codigo")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Libro")
                        .HasColumnName("libro")
                        .HasMaxLength(45);

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasMaxLength(200);

                    b.Property<string>("Sexo")
                        .HasColumnName("sexo")
                        .HasMaxLength(45);

                    b.HasKey("Idfirmas");

                    b.ToTable("firmas");
                });

            modelBuilder.Entity("scorpioweb.Models.Fraccionesimpuestas", b =>
                {
                    b.Property<int>("IdFracciones")
                        .HasColumnName("idFracciones");

                    b.Property<int>("SupervisionIdSupervision")
                        .HasColumnName("Supervision_idSupervision");

                    b.Property<string>("Autoridad")
                        .HasMaxLength(100);

                    b.Property<string>("Estado")
                        .HasMaxLength(45);

                    b.Property<string>("Evidencia")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaTermino")
                        .HasColumnType("datetime");

                    b.Property<string>("FiguraJudicial")
                        .HasMaxLength(45);

                    b.Property<string>("Tipo")
                        .HasMaxLength(4);

                    b.HasKey("IdFracciones", "SupervisionIdSupervision");

                    b.HasIndex("SupervisionIdSupervision")
                        .HasName("fk_FraccionesImpuestas_Supervision_idx");

                    b.ToTable("fraccionesimpuestas");
                });

            modelBuilder.Entity("scorpioweb.Models.Municipios", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<int>("EstadosId")
                        .HasColumnName("estados_id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnName("municipio")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("municipios");
                });

            modelBuilder.Entity("scorpioweb.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasColumnName("idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("Alias")
                        .HasMaxLength(45);

                    b.Property<string>("Celular")
                        .HasMaxLength(45);

                    b.Property<string>("ConsumoSustancias")
                        .HasMaxLength(45);

                    b.Property<string>("Curp")
                        .HasColumnName("CURP")
                        .HasMaxLength(45);

                    b.Property<string>("DatosGeneralescol")
                        .HasMaxLength(100);

                    b.Property<string>("Duracion")
                        .HasMaxLength(45);

                    b.Property<int?>("Edad")
                        .HasColumnType("int(11)");

                    b.Property<string>("EspecifiqueIdioma")
                        .HasMaxLength(45);

                    b.Property<string>("EspecifiqueTraductor")
                        .HasMaxLength(100);

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(45);

                    b.Property<string>("Familiares");

                    b.Property<DateTime?>("Fnacimiento")
                        .HasColumnName("FNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("Genero")
                        .HasMaxLength(45);

                    b.Property<string>("Hijos")
                        .HasMaxLength(45);

                    b.Property<string>("LeerEscribir")
                        .HasMaxLength(45);

                    b.Property<string>("Lnestado")
                        .HasColumnName("LNEstado")
                        .HasMaxLength(45);

                    b.Property<string>("Lnlocalidad")
                        .HasColumnName("LNLocalidad")
                        .HasMaxLength(45);

                    b.Property<string>("Lnmunicipio")
                        .HasColumnName("LNMunicipio")
                        .HasMaxLength(45);

                    b.Property<string>("Lnpais")
                        .HasColumnName("LNPais")
                        .HasMaxLength(45);

                    b.Property<string>("Materno")
                        .HasMaxLength(45);

                    b.Property<int?>("Nhijos")
                        .HasColumnName("NHijos")
                        .HasColumnType("int(11)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100);

                    b.Property<int?>("NpersonasVive")
                        .HasColumnName("NPersonasVive")
                        .HasColumnType("int(11)");

                    b.Property<string>("OtroIdioma")
                        .HasMaxLength(45);

                    b.Property<string>("Paterno")
                        .HasMaxLength(45);

                    b.Property<string>("Propiedades")
                        .HasMaxLength(45);

                    b.Property<string>("ReferenciasPersonales");

                    b.Property<string>("Supervisor")
                        .HasMaxLength(100);

                    b.Property<string>("TelefonoFijo")
                        .HasMaxLength(45);

                    b.Property<string>("Traductor")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("UltimaActualización")
                        .HasColumnType("datetime");

                    b.Property<string>("rutaFoto");

                    b.HasKey("IdPersona");

                    b.ToTable("persona");
                });

            modelBuilder.Entity("scorpioweb.Models.Personacausapenal", b =>
                {
                    b.Property<int>("IdPersonaCausapenal")
                        .HasColumnName("idPersonaCausapenal");

                    b.Property<int>("CausaPenalIdCausaPenal")
                        .HasColumnName("CausaPenal_idCausaPenal");

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("persona_idPersona");

                    b.HasKey("IdPersonaCausapenal");

                    b.HasIndex("CausaPenalIdCausaPenal")
                        .HasName("fk_PersonaCausaPenal_CausaPenal_idx");

                    b.HasIndex("PersonaIdPersona")
                        .HasName("fk_PersonaCausaPenal_Persona_idx");

                    b.ToTable("personacausapenal");
                });

            modelBuilder.Entity("scorpioweb.Models.Planeacionestrategica", b =>
                {
                    b.Property<int>("IdPlaneacionEstrategica")
                        .HasColumnName("idPlaneacionEstrategica");

                    b.Property<int>("SupervisionIdSupervision")
                        .HasColumnName("Supervision_idSupervision");

                    b.Property<string>("DiaFirma")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInforme")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaProximoContacto")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaUltimoContacto")
                        .HasColumnType("datetime");

                    b.Property<string>("MotivoNoPlaneacion")
                        .HasMaxLength(45);

                    b.Property<string>("PeriodicidadFirma")
                        .HasMaxLength(45);

                    b.Property<string>("PlanSupervision")
                        .HasMaxLength(2);

                    b.Property<string>("UltimoInforme")
                        .HasMaxLength(45);

                    b.HasKey("IdPlaneacionEstrategica", "SupervisionIdSupervision");

                    b.HasIndex("SupervisionIdSupervision")
                        .HasName("fk_PlaneacionEstrategica_Supervision_idx");

                    b.ToTable("planeacionestrategica");
                });

            modelBuilder.Entity("scorpioweb.Models.Proceso", b =>
                {
                    b.Property<int>("IdProceso")
                        .HasColumnName("idProceso")
                        .HasColumnType("int(11)");

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("CausaPenal")
                        .HasMaxLength(50);

                    b.Property<string>("Coimputados")
                        .HasMaxLength(45);

                    b.Property<string>("CoimputadosSupervision")
                        .HasMaxLength(45);

                    b.Property<string>("EspecificaFuncionario")
                        .HasMaxLength(100);

                    b.Property<string>("EspecificaRelacion")
                        .HasMaxLength(100);

                    b.Property<string>("Funcionario")
                        .HasMaxLength(45);

                    b.Property<int?>("NoCoimputadosSupervision")
                        .HasColumnType("int(11)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(100);

                    b.Property<string>("RelacionLugar")
                        .HasMaxLength(45);

                    b.Property<string>("RelacionSupervisado")
                        .HasMaxLength(45);

                    b.HasKey("IdProceso", "PersonaIdPersona");

                    b.ToTable("proceso");
                });

            modelBuilder.Entity("scorpioweb.Models.Revocacion", b =>
                {
                    b.Property<int>("IdRevocacion")
                        .HasColumnName("idRevocacion");

                    b.Property<int>("SupervisionIdSupervision")
                        .HasColumnName("Supervision_idSupervision");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime");

                    b.Property<string>("MotivoRevocacion")
                        .HasMaxLength(70);

                    b.Property<string>("Revocado")
                        .HasMaxLength(2);

                    b.HasKey("IdRevocacion", "SupervisionIdSupervision");

                    b.HasIndex("SupervisionIdSupervision")
                        .HasName("fk_Revocacion_Supervision_idx");

                    b.ToTable("revocacion");
                });

            modelBuilder.Entity("scorpioweb.Models.Saludfisica", b =>
                {
                    b.Property<int>("IdSaludFisica")
                        .HasColumnName("idSaludFisica")
                        .HasColumnType("int(11)");

                    b.Property<string>("Discapacidad")
                        .HasMaxLength(2);

                    b.Property<string>("EmbarazoLactancia")
                        .HasMaxLength(2);

                    b.Property<string>("Enfermedad")
                        .HasMaxLength(2);

                    b.Property<string>("EspecifiqueDiscapacidad")
                        .HasMaxLength(100);

                    b.Property<string>("EspecifiqueEnfermedad")
                        .HasMaxLength(100);

                    b.Property<string>("EspecifiqueServicioMedico")
                        .HasMaxLength(45);

                    b.Property<string>("InstitucionServicioMedico")
                        .HasMaxLength(45);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("ServicioMedico")
                        .HasMaxLength(45);

                    b.Property<string>("Tiempo")
                        .HasMaxLength(100);

                    b.Property<string>("Tratamiento")
                        .HasMaxLength(200);

                    b.HasKey("IdSaludFisica");

                    b.ToTable("saludfisica");
                });

            modelBuilder.Entity("scorpioweb.Models.Supervision", b =>
                {
                    b.Property<int>("IdSupervision")
                        .HasColumnName("idSupervision");

                    b.Property<int>("CausaPenalIdCausaPenal")
                        .HasColumnName("CausaPenal_idCausaPenal");

                    b.Property<string>("EstadoCumplimiento")
                        .HasMaxLength(45);

                    b.Property<string>("EstadoSupervision")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("Inicio")
                        .HasColumnType("datetime");

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona");

                    b.Property<DateTime?>("Termino")
                        .HasColumnType("datetime");

                    b.HasKey("IdSupervision");

                    b.HasIndex("CausaPenalIdCausaPenal")
                        .HasName("fk_Supervision_CausaPenal_idx");

                    b.HasIndex("PersonaIdPersona")
                        .HasName("fk_Supervision_persona_idx");

                    b.ToTable("supervision");
                });

            modelBuilder.Entity("scorpioweb.Models.Suspensionseguimiento", b =>
                {
                    b.Property<int>("IdSuspensionSeguimiento")
                        .HasColumnName("idSuspensionSeguimiento");

                    b.Property<int>("SupervisionIdSupervision")
                        .HasColumnName("Supervision_idSupervision");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime");

                    b.Property<string>("MotivoSuspension")
                        .HasMaxLength(100);

                    b.Property<string>("Suspendido")
                        .HasMaxLength(2);

                    b.HasKey("IdSuspensionSeguimiento", "SupervisionIdSupervision");

                    b.HasIndex("SupervisionIdSupervision")
                        .HasName("fk_SuspensionSeguimiento_Supervision_idx");

                    b.ToTable("suspensionseguimiento");
                });

            modelBuilder.Entity("scorpioweb.Models.Trabajo", b =>
                {
                    b.Property<int>("IdTrabajo")
                        .HasColumnName("idTrabajo")
                        .HasColumnType("int(11)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150);

                    b.Property<string>("EmpledorJefe")
                        .HasMaxLength(100);

                    b.Property<string>("EnteradoProceso")
                        .HasMaxLength(2);

                    b.Property<string>("Horario")
                        .HasMaxLength(100);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("Puesto")
                        .HasMaxLength(45);

                    b.Property<string>("Salario")
                        .HasMaxLength(45);

                    b.Property<string>("SePuedeEnterar")
                        .HasMaxLength(2);

                    b.Property<string>("Telefono")
                        .HasMaxLength(45);

                    b.Property<string>("TemporalidadSalario")
                        .HasMaxLength(45);

                    b.Property<string>("TiempoTrabajano")
                        .HasMaxLength(45);

                    b.Property<string>("TipoOcupacion")
                        .HasMaxLength(150);

                    b.Property<string>("Trabaja")
                        .HasMaxLength(2);

                    b.HasKey("IdTrabajo");

                    b.ToTable("trabajo");
                });

            modelBuilder.Entity("scorpioweb.Models.Victima", b =>
                {
                    b.Property<int>("IdVictima")
                        .HasColumnName("idVictima");

                    b.Property<int>("SupervisionIdSupervision")
                        .HasColumnName("Supervision_idSupervision");

                    b.Property<string>("ConoceDetenido")
                        .HasMaxLength(2);

                    b.Property<string>("Direccion")
                        .HasMaxLength(300);

                    b.Property<string>("Edad")
                        .HasMaxLength(45);

                    b.Property<string>("Nombre")
                        .HasMaxLength(150);

                    b.Property<string>("Telefono")
                        .HasMaxLength(10);

                    b.Property<string>("TiempoConocerlo")
                        .HasMaxLength(75);

                    b.Property<string>("TipoRelacion")
                        .HasMaxLength(100);

                    b.Property<string>("Victimacol")
                        .HasColumnName("victimacol")
                        .HasMaxLength(45);

                    b.Property<string>("ViveSupervisado")
                        .HasMaxLength(45);

                    b.HasKey("IdVictima", "SupervisionIdSupervision");

                    b.HasIndex("SupervisionIdSupervision")
                        .HasName("fk_Victima_Supervision_idx");

                    b.ToTable("victima");
                });
#pragma warning restore 612, 618
        }
    }
}
